# Generated by Django 4.1.4 on 2023-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrations',
            name='cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='illustrations',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='illustrations',
            name='home_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='illustrations',
            name='rows',
            field=models.IntegerField(default=1),
        ),
    ]
